lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CodeStatsWeb.RememberMePlug
    plug CodeStatsWeb.SetSessionUserPlug
  end

  pipeline :browser_auth do
    plug CodeStatsWeb.AuthRequiredPlug
  end

  pipeline :browser_unauth do
    plug CodeStatsWeb.AuthNotAllowedPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug CodeStatsWeb.APIAuthRequiredPlug
  end

  scope "/", CodeStatsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/api-docs", PageController, :api_docs
    get "/tos", PageController, :terms
    get "/plugins", PageController, :plugins
    get "/changes", PageController, :changes

    get "/aliases", AliasController, :list

    get "/battle", BattleController, :battle

    scope "/" do
      pipe_through :browser_unauth

      get "/login", AuthController, :render_login
      post "/login", AuthController, :login
      get "/signup", AuthController, :render_signup
      post "/signup", AuthController, :signup
      get "/forgot-password", AuthController, :render_forgot
      post "/forgot-password", AuthController, :forgot
      get "/reset-password/:token", AuthController, :render_reset
      put "/reset-password/:token", AuthController, :reset
    end

    get "/logout", AuthController, :logout

    get "/users/:username", ProfileController, :profile

    scope "/my" do
      pipe_through :browser_auth

      get "/profile", ProfileController, :my_profile

      get "/preferences", PreferencesController, :edit
      put "/preferences", PreferencesController, :do_edit

      post "/password", PreferencesController, :change_password
      post "/sound_of_inevitability", PreferencesController, :delete

      get "/machines", MachineController, :list
      post "/machines", MachineController, :add
      get "/machines/:id", MachineController, :view_single
      put "/machines/:id", MachineController, :edit
      delete "/machines/:id", MachineController, :delete
      post "/machines/:id/activate", MachineController, :activate
      post "/machines/:id/deactivate", MachineController, :deactivate
      post "/machines/:id/key", MachineController, :regen_machine_key
    end
  end

  scope "/api", CodeStatsWeb do
    pipe_through :api

    get "/users/:username", ProfileController, :profile_api

    scope "/my" do
      pipe_through :api_auth

      post "/pulses", PulseController, :add
    end
  end
end

lib/code_stats_web/templates/page/api_docs.html.eex
<div class="stripe">
  <h1>
    API documentation <sup>(v. 1.0.1)</sup>
  </h1>

  <h2>
    Table of Contents
  </h2>

  <p>
    <ol>
      <li>
        <a href="#basics">Basics</a>
      </li>
      <li>
        <a href="#terms">Terms</a>
      </li>
      <li>
        <a href="#auth">Authentication</a>
      </li>
      <li>
        <a href="#profile">Endpoint: Profile</a>
      </li>
      <li>
        <a href="#pulse">Endpoint: Pulse</a>
      </li>
    </ol>
  </p>

  <h2>
    Basics <a id="basics" href="#basics">#</a>
  </h2>

  <h3>API version</h3>

  <p>
    The API follows <a href="http://semver.org/">Semantic Versioning</a>. That means bugfixes bump the patch version, backwards compatible features bump the minor version and backwards incompatible changes bump the major version.
  </p>

  <h3>Protocol</h3>

  <p>
    All requests are made using HTTP and use JSON to serialize the data. Requests with payloads should send the payload as JSON in the request body. The responses are JSON, error responses will contain the key <code>error</code> which has the error message as value. The error message is a human readable message, not intended for automated parsing.
  </p>

  <h3>Path</h3>

  <p>
    All API paths are prefixed with <code>/api</code>.
  </p>

  <h3>HTTPS</h3>

  <p>
    All requests must be secured using HTTPS. Plain HTTP requests will not be accepted.
  </p>

  <h3>Timestamps</h3>

  <p>
    Datetime timestamps should be sent as RFC 3339 datetime values and include the timezone offset. Example: <code>2016-04-24T01:43:56+12:00</code>.
  </p>

  <h2>
    Terms <a id="terms" href="#terms">#</a>
  </h2>

  <h3>XP</h3>

  <p>
    Programming gives users <em>experience points</em>, i.e. XP. A certain amount of XP corresponds to a certain level. In Code::Stats, each keystroke that creates or deletes a character gives 1 XP, so a client should keep an XP counter and add to it on each such keystroke. Operating on many characters at once, such as when deleting highlighted text, is counted as 1 XP, if made possible by the editor's API. An XP value is a positive integer.
  </p>

  <h3>Level</h3>

  <p>
    A <em>level</em> is a human readable indicator of progress. It is calculated from XP and its only purpose is to make an amount of XP more meaningful for a user. The read API does not provide levels, so it is the client's job to calculate the levels of a user.
  </p>

  <p>
    Levels are calculated with the following pseudocode formula:
  </p>

  <pre><code>LEVEL_FACTOR = 0.025

// Get level for given XP
int get_level(float xp) {
  return to_int(floor(LEVEL_FACTOR * sqrt(xp)))
}</code></pre>

  <p>
    For more examples of level calculations, see <a href="https://github.com/Nicd/code-stats/blob/master/lib/code_stats/language/xp_calculator.ex">CodeStats.Language.XPCalculator</a>.
  </p>

  <h3>Language</h3>

  <p>
    XP is always tied to a <em>language</em>. This can be a programming language, but also some other syntax edited by the users, such as Markdown or JSON. Detecting the active language is the client's responsibility. This can be done, for example, based on the active syntax highlighting language or the file's extension. Languages are referred to by their names as strings.
  </p>

  <h3>Pulse</h3>

  <p>
    A <em>pulse</em> is a collection of XPs for different languages. Pulses should be added periodically by the client and should contain the languages used and the XPs accumulated since the last pulse. They should also contain the time the pulse was created. This way they can be sent later, if the user's Internet connection is down for the moment. Pulses that are more than a week old will not be accepted by the API.
  </p>

  <h2>
    Authentication <a id="auth" href="#auth">#</a>
  </h2>

  <p>
    Code::Stats uses simple token authentication. A single token authenticates both a user and the machine they are using. It is signed to prevent tampering and unauthorized creation of tokens matching other users' information. To generate a token, you need to create a new machine from the <a href="<%= machine_path(@conn, :list) %>">Machine control panel</a>. A token looks like this:
  </p>

  <pre><code>SFMyNTY.OEotWWdnPT0jI01qaz0.X0wVEZquh8Ogau1iTtBihYqqL71FD8N6p5ChQiIpaxQ</code></pre>

  <p>
    In all API requests that require authentication, the token must be added using the HTTP header <code>X-API-Token</code>. Here is an example request sent with the token (as printed by curl):
  </p>

  <pre><code>&gt; POST /api/my/pulses HTTP/1.1
&gt; Host: codestats.net:443
&gt; User-Agent: curl/7.43.0
&gt; Accept: */*
&gt; X-API-Token: SFMyNTY.OEotWWdnPT0jI01qaz0.X0wVEZquh8Ogau1iTtBihYqqL71FD8N6p5ChQiIpaxQ
&gt; Content-Type: application/json
&gt; Content-Length: 113</code></pre>

  <h2>
    Endpoint: Profile <a id="profile" href="#profile">#</a>
  </h2>

  <h3>
    Read public user's information
  </h3>

  <p>
    <code>GET <%= profile_path(@conn, :profile_api, "username") %></code>
  </p>

  <p>
    Retrieves the information of the specified user. If the user does not exist or their profile is private, <code>HTTP 404</code> will be returned. An example request that also shows the returned data format:
  </p>

  <pre><code>GET /api/users/Nicd HTTP/1.1

{
  "user": "Nicd",
  "total_xp": 3073421,
  "new_xp": 3289,
  "machines": {
    "Työkone": {
      "xps": 246116,
      "new_xps": 3289
    },
    "Best Machine": {
      "xps": 2827305,
      "new_xps": 0
    }
  },
  "languages": {
    "💩": {
      "xps": 1767278,
      "new_xps": 0
    },
    "XML": {
      "xps": 15,
      "new_xps": 0
    },
    "Plaintext": {
      "xps": 3429,
      "new_xps": 3289
    }
  },
  "dates": {
    "2016-12-31": 3289,
    "2016-08-24": 26700
  }
}</code></pre>

  <p>
    <strong>Returns</strong> user profile data as JSON. In the data, <code>new_xps</code> is XP gained in the last 12 hours.
  </p>

  <h2>
    Endpoint: Pulse <a id="pulse" href="#pulse">#</a>
  </h2>

  <h3>
    Add pulse <sup>(authn required)</sup>
  </h3>

  <p>
    <code>POST <%= pulse_path(@conn, :add) %></code>
  </p>

  <p>
    Adds a new <em>Pulse</em> to the system. The client should send a pulse periodically when the user is programming. The payload should be a list of languages and their accumulated XP since the last successful pulse. The pulse must also contain a <code>coded_at</code> timestamp that signifies when the pulse was generated. This allows sending the pulse later, if the Internet connection is momentarily cut.
  </p>

  <p>
    <strong>Note:</strong> The <code>coded_at</code> timestamp <strong>MUST</strong> be in the user's local time with their local UTC offset. Do not convert the time to UTC before sending it to the API.
  </p>

  <p>
    Note: The <code>coded_at</code> timestamp must be no older than a week. Any older timestamps will result in an error. Timestamps in the future will be ignored, their <code>coded_at</code> will be set to the current moment.
  </p>

  <p>
    Example payload:
  </p>

  <pre><code>{
  "coded_at": "2016-04-24T01:43:56+12:00",
  "xps": [
    {"language": "C++",    "xp": 15},
    {"language": "Elixir", "xp": 30},
    {"language": "EEx",    "xp": 3}
  ]
}</code></pre>

  <p><strong>Returns</strong> <code>HTTP 201</code> and <code>{"ok": "Great success!"}</code> on success.</p>
</div>

lib/code_stats_web/templates/page/changes.html.eex
<div class="stripe">
  <h1>Source</h1>

  <p>
    Code::Stats and its plugins are open source software, licensed under the 3-clause BSD licence. You can study the inner workings of the code and suggest improvements. You are also free to fork the code.
  </p>

  <h2>Code repositories</h2>

  <p>
    <ul>
      <li>
        <strong>Code::Stats main site:</strong>
        <a href="https://gitlab.com/code-stats/code-stats">code-stats/code-stats</a>
      </li>

      <li>
        <strong>Atom plugin:</strong>
        <a href="https://gitlab.com/code-stats/code-stats-atom">code-stats/code-stats-atom</a>
      </li>

      <li>
        <strong>JetBrains plugin:</strong>
        <a href="https://gitlab.com/code-stats/code-stats-intellij">code-stats/code-stats-intellij</a>
      </li>

      <li>
        <strong>Sublime Text 3 plugin:</strong>
        <a href="https://gitlab.com/code-stats/code-stats-sublime">code-stats/code-stats-sublime</a>
      </li>
    </ul>
  </p>
</div>

<div class="stripe stripe-accent contributors">
  <h2>Contributors</h2>

  <div class="contributors-list">
    <div>
      <img src="<%= static_path(@conn, "/frontend/assets/images/contributors/nicd.png") %>" alt="Mikko Ahlroth" title="Mikko Ahlroth" />

      <h3>Mikko Ahlroth</h3>
      <p class="subtitle">Lead developer</p>

      <p>
        <a href="https://blog.nytsoi.net/">Blog</a>
        / <a href="https://github.com/Nicd">GitHub</a>
        / <a href="https://gitlab.com/Nicd">GitLab</a>
      </p>
    </div>

    <div>
      <img src="<%= static_path(@conn, "/frontend/assets/images/Logo.svg") %>" alt="Code::Stats logo" />

      <h3>Hannu Hartikainen</h3>
      <p class="subtitle"><a href="">code-stats-zsh</a> developer</p>

      <p>
        <a href="https://github.com/dancek">GitHub</a>
      </p>
    </div>

    <div>
      <img src="<%= static_path(@conn, "/frontend/assets/images/contributors/nikolauska.png") %>" alt="Niko Lehtovirta" title="Niko Lehtovirta" />

      <h3>Niko Lehtovirta</h3>

      <p>
        <a href="https://github.com/nikolauska">GitHub</a>
        / <a href="https://gitlab.com/nikolauska">GitLab</a>
      </p>
    </div>

    <div>
      <img src="<%= static_path(@conn, "/frontend/assets/images/contributors/aman.jpeg") %>" alt="Aman Mittal" title="Aman Mittal" />

      <h3>Aman Mittal</h3>
      <p class="subtitle"><a href="https://gitlab.com/code-stats/codestats-cli">codestats-cli</a> developer</p>

      <p>
        <a href="https://github.com/amandeepmittal">GitHub</a>
      </p>
    </div>

    <div>
      <img src="<%= static_path(@conn, "/frontend/assets/images/contributors/riussi.jpg") %>" alt="Juha Ristolainen" title="Juha Ristolainen" />

      <h3>Juha Ristolainen</h3>
      <p class="subtitle"><a href="https://marketplace.visualstudio.com/items?itemName=juha-ristolainen.code-stats-vscode">code-stats-vscode</a> developer</p>

      <p>
        <a href="https://github.com/riussi">GitHub</a>
        / <a href="https://twitter.com/riussi">Twitter</a>
        / <a href="http://www.juharistolainen.com/">Site</a>
      </p>
    </div>

    <div>
      <img src="<%= static_path(@conn, "/frontend/assets/images/contributors/mastorm.png") %>" alt="Mathias Storm" title="Mathias Storm" />

      <h3>Mathias Storm</h3>
      <p class="subtitle"><a href="https://marketplace.visualstudio.com/items?itemName=MathiasSTorm.CodeStatsClient">CodeStats.Client</a> developer</p>

      <p>
        <a href="https://github.com/mastorm">GitHub</a>
      </p>
    </div>
  </div>
</div>

<div class="stripe">
  <h2>Changelog</h2>

  <h3>2.0.0 – ????-??-?? – Brand spanking new</h3>

  <ul>
    <li>Totally new UI written with CSS Grid.</li>
    <li>New graphs written with RE:DOM.</li>
  </ul>

  <h3>1.8.6 – 2017-10-02 – AppSignal filtering</h3>

  <ul>
    <li>Filtered out some data that doesn't need to go to AppSignal.</li>
  </ul>

  <h3>1.8.5 – 2017-10-01 – AppSignal &amp; token expiration</h3>

  <ul>
    <li>Added AppSignal integration for metrics and error reports to aid in development.</li>
    <li>Added token expiration to channels so that you need to refresh the page at least once every 3 months.</li>
  </ul>

  <h3>1.8.4 – 2017-10-01 – Updated to Elixir 1.5, bumped deps</h3>

  <ul>
    <li>So I kind of blew up the thing accidentally while restarting it. Now it is fixed.</li>
  </ul>

  <h3>1.8.3 – 2017-07-16 – Small fixes</h3>

  <ul>
    <li>Fixed the "private profile" checkbox not working properly in the preferences page.</li>
    <li>Added support for CORS into the user profile read API.</li>
  </ul>

  <h3>1.8.2 – 2017-04-09 – Groundwork for future refactoring</h3>

  <ul>
    <li>Added the storing of the user's local timestamp and timezone offset when creating pulses. This will be used for better graphs in the future.</li>
    <li>Added note about the VSCode plugin to the plugins page.</li>
  </ul>

  <h3>1.8.1 – 2017-01-18 – Fixes + Sublime Text 3 support</h3>

  <ul>
    <li>Bumped Elixir version to 1.4 and fixed compilation warnings.</li>
    <li>Fix decimals being printed wrong with Elixir 1.4.</li>
    <li>Added information about new Sublime Text 3 plugin.</li>
    <li>Added editor logos to plugin page.</li>
  </ul>

  <h3>1.8.0 – 2017-01-02 – Language aliases</h3>

  <ul>
    <li>Added a language alias feature. Now some languages are just aliases for others. This is done to fix typos and problems in language detection in editors. For example, "JavaScript 1.5" (which was released in 2000 and is erroneously detected by JetBrains in some situations) will now be corrected to "JavaScript" and all existing XP has been combined between the languages. If you have feedback or suggestions on languages to merge, give us feedback on our Gitter or IRC channel.</li>
    <li>Added information about Gitter channel into footer, removed useless contact page.</li>
    <li>Added user profile API for fetching data of public users. Integrate Code::Stats with your website! Check the <a href="<%= page_path(@conn, :api_docs) %>">API documentation</a> for more information.</li>
  </ul>

  <h3>1.7.2 – 2016-09-12 – Machine API key and caching duration stuff</h3>

  <ul>
    <li>Fixed machine API key changing when machine name was changed.</li>
    <li>Added caching duration to user's cache to monitor how long generating caches takes. ⏱</li>
    <li>Fixed duplicate update query when updating user's cache.</li>
  </ul>

  <h3>1.7.1 – 2016-09-03 – Small fixes to live updates</h3>

  <ul>
    <li>Fixed machine ordering on profile page being wrong when live updating.</li>
    <li>Fixed live updates not working on IE and other silly browsers by adding Babel polyfill.</li>
  </ul>

  <h3>1.7.0 – 2016-08-25 – Live updates ✨</h3>

  <ul>
    <li>Added live update functionality to profile page and index page. XP numbers and progress bars update live using Elm. 📊 Index page includes a ticker that shows users gaining XP live (private profiles are shown as "Private user").</li>
    <li>Bumped dependencies. Update of Plug results in a different format for API tokens, but the old ones will still work.</li>
  </ul>

  <h3>1.6.2 – 2016-08-08 – Small fixes</h3>

  <ul>
    <li>Remove redundant ARIA tags from progress bars to show more descriptive textual info for screen readers.</li>
    <li>Fix error message printed in console when trying to access a page that does not allow authentication, while being logged in.</li>
  </ul>

  <h3>1.6.1 – 2016-08-06 – Fixes to machines and page permissions</h3>

  <ul>
    <li>Forbid authenticated users from accessing the login, signup and password reset pages. They will be redirected to their profile instead.</li>
    <li>Fix crash when machine was deleted, caused by the cache not being regenerated. Now the cache is regenerated automatically after delete and crash is avoided even if regeneration is still in progress.</li>
    <li>Add a JavaScript confirmation prompt when deleting a machine.</li>
  </ul>

  <h3>1.6.0 – 2016-08-04 – Password resets and fixes</h3>

  <ul>
    <li>Added password reset feature. Password can only be reset if the account has an email address set up.</li>
    <li>Updated privacy policy and terms of service due to email sending feature.</li>
    <li>Fixed 💥 when forms like the signup form were filled with invalid data.</li>
    <li>Fixed crash when pulses were sent before caches were generated.</li>
    <li>Fixed crash when pulses were sent with the API token in an invalid format.</li>
    <li>Added Twitter link.</li>
    <li>Added Elixir and Phoenix link to footer.</li>
    <li>Fixed discrepancies in the API docs regarding pulse dates.</li>
    <li>An issue with the "last coded at" date in 1.5.0 was hotfixed.</li>
  </ul>

  <h3>1.5.0 – 2016-07-17 – Second performance update</h3>

  <ul>
    <li>Earlier, profile view XPs per language were cached to the database as CachedXP elements. This worked fine for that purpose but caching for other dimensions such as per machine and per date were needed. In this update, CachedXP is removed in favor of a JSON field on the user model, which can be used to add all kinds of different caches. Caching is implemented in this field for languages, machines and dates. This removes the need to hit the database for other uses than to update the cache and to load the last 12 hours' XP data. As a result the profile view's display should be much faster.</li>
    <li>An issue with 1.4.0 and database limits in queries was hotfixed.</li>
  </ul>

  <h3>1.4.0 – 2016-07-16 – First performance update</h3>

  <ul>
    <li>Total XP and most popular languages counters on the front page are now in-memory, stored inside ETS. They are updated on every incoming pulse (for now) and totally refreshed every 15 minutes. This should make the front page much faster.</li>
    <li>Added an index to make "XP in last 12 hours" queries faster both on front page and profile pages.</li>
    <li>Accessibility was improved with regards to dates and progress bars.</li>
    <li>Fixed average XP per day display, which showed XP in scientific format in some cases.</li>
    <li>Added real page titles for better SEO and bookmarking.</li>
    <li>Updated the codebase for Elixir 1.3, Phoenix 1.2 and Ecto 2.0.</li>
    <li>Fixed some JSON errors not being sent correctly in the API.</li>
  </ul>

  <h3>1.3.7 – 2016-06-08 – Fix username uniqueness</h3>

  <ul>
    <li>Fix username uniqueness, due to a problem with SQL migrations a unique index was not created and multiple users could be registered with the same username. 😱</li>
    <li>Change some IDs to bigint because if it's worth doing, it's worth overdoing.</li>
    <li>Remove old unused total XP property from users.</li>
    <li>Clarified git repo licences a bit.</li>
  </ul>

  <h3>1.3.3–1.3.6 – 2016-06-07 – JetBrains and username path fixes</h3>

  <ul>
    <li>Added details of the published IntelliJ/JetBrains plugin.</li>
    <li>Fixed spaces in usernames resulting in unreachable profile pages.</li>
    <li>Disallowed the plus sign in usernames to avoid conflicts with spaces.</li>
  </ul>

  <h3>1.3.2 – 2016-06-06 – JSON errors</h3>

  <ul>
    <li>Enabled JSON errors for easier debugging of 500 Internal server errors.</li>
  </ul>

  <h3>1.3.1 – 2016-06-05 – Language name fix</h3>

  <ul>
    <li>Fixed languages being created with different capitalisations. Now language names are case insensitive.</li>
  </ul>

  <h3>1.3.0 – 2016-06-04 – Machine stats</h3>

  <ul>
    <li>Added machine statistics to profile page.</li>
    <li>Added recalculation of XP once a day to fix XP errors in profile view.</li>
    <li>Added favicons.</li>
    <li>Added more user info to profile view.</li>
  </ul>

  <h3>1.2.2 – 2016-06-02 – Vincit Oy</h3>

  <ul>
    <li>Added note about my company who have sponsored the development of the service.</li>
    <li>Added more information to the plugins page.</li>
  </ul>

  <h3>1.2.1 – 2016-05-31 – Small fixes</h3>

  <ul>
    <li>Fix <a href="https://github.com/Nicd/code-stats/issues/1">#1</a>: coded_at time range not documented in API docs</li>
    <li>Fix <a href="https://github.com/Nicd/code-stats/issues/2">#2</a>: Endpoint path typo in API docs</li>
    <li>Fix <a href="https://github.com/Nicd/code-stats/issues/4">#4</a>: Refactor README</li>
    <li>Fix <a href="https://github.com/Nicd/code-stats/issues/5">#5</a>: Add link to example stats to front page</li>
    <li>Fix <a href="https://github.com/Nicd/code-stats/issues/6">#6</a>: Add clarification about recent XP</li>
  </ul>

  <h3>1.2.0 – 2016-05-31 – Scaling back levels</h3>

  <ul>
    <li>Scaled back the level algorithm to grant less levels. XP is not affected. The aim is to prevent an inflation of levels. The level algorithm may be modified further later on.</li>
    <li>Combined the source and changes page.</li>
  </ul>

  <h3>1.1.1 – 2016-05-30 – Clock drift</h3>

  <ul>
    <li>Fixed a case where clock drift either on the client or the server caused pulses to not be accepted.</li>
  </ul>

  <h3>1.1.0 – 2016-05-30 – First public release</h3>

  <p>
    Implemented <em>everything</em>. 🎉
  </p>
</div>

lib/code_stats_web/templates/page/index.html.eex
<section class="stripe stripe-accent" id="global-user-map-graph">
    <div id="world-map-graph"></div>
    <div id="history-bar-graph"></div>

  <noscript>
    <h2>JavaScript required</h2>
    <p>
      This website uses JavaScript for displaying graphs. You can use the site with
      JavaScript turned off, but you will be missing out on some of the content.
    </p>
  </noscript>
</section>

<section id="frontpage-ads" class="stripe">
  <section class="frontpage-ad">
    <h3>Write code</h3>
    <p>
      Code::Stats has plugins for various editors. If you wish to make one for your own favourite editor, you are free to check out the API documentation!
    </p>
  </section>
  <section class="frontpage-ad">
    <h3>
      Level up
    </h3>
    <p>
      You will be awarded with experience points for the amount of programming you do. Watch as your levels grow for each language you use. Identify your strong skill sets and use the data to see where you still have room for improvement.
    </p>
  </section>
  <section class="frontpage-ad">
    <h3>
      Show off
    </h3>
    <p>
      Show your personal statistics page to your friends and compare your progress with others. Maybe even have a competition! Or, if you wish, you can keep all your information private and enjoy it in secret.
    </p>

    <p>
      <a class="button" href="">
        See example profile
      </a>
    </p>
  </section>
</section>