lib/code_stats_web/router.ex
defmodule CodeStatsWeb.Router do
  use CodeStatsWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug CodeStatsWeb.RememberMePlug
    plug CodeStatsWeb.SetSessionUserPlug
  end

  pipeline :browser_auth do
    plug CodeStatsWeb.AuthRequiredPlug
  end

  pipeline :browser_unauth do
    plug CodeStatsWeb.AuthNotAllowedPlug
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  pipeline :api_auth do
    plug CodeStatsWeb.APIAuthRequiredPlug
  end

  scope "/", CodeStatsWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index

    get "/api-docs", PageController, :api_docs
    get "/tos", PageController, :terms
    get "/plugins", PageController, :plugins
    get "/changes", PageController, :changes

    get "/aliases", AliasController, :list

    get "/battle", BattleController, :battle

    scope "/" do
      pipe_through :browser_unauth

      get "/login", AuthController, :render_login
      post "/login", AuthController, :login
      get "/signup", AuthController, :render_signup
      post "/signup", AuthController, :signup
      get "/forgot-password", AuthController, :render_forgot
      post "/forgot-password", AuthController, :forgot
      get "/reset-password/:token", AuthController, :render_reset
      put "/reset-password/:token", AuthController, :reset
    end

    get "/logout", AuthController, :logout

    get "/users/:username", ProfileController, :profile

    scope "/my" do
      pipe_through :browser_auth

      get "/profile", ProfileController, :my_profile

      get "/preferences", PreferencesController, :edit
      put "/preferences", PreferencesController, :do_edit

      post "/password", PreferencesController, :change_password
      post "/sound_of_inevitability", PreferencesController, :delete

      get "/machines", MachineController, :list
      post "/machines", MachineController, :add
      get "/machines/:id", MachineController, :view_single
      put "/machines/:id", MachineController, :edit
      delete "/machines/:id", MachineController, :delete
      post "/machines/:id/activate", MachineController, :activate
      post "/machines/:id/deactivate", MachineController, :deactivate
      post "/machines/:id/key", MachineController, :regen_machine_key
    end
  end

  scope "/api", CodeStatsWeb do
    pipe_through :api

    get "/users/:username", ProfileController, :profile_api

    scope "/my" do
      pipe_through :api_auth

      post "/pulses", PulseController, :add
    end
  end
end

lib/code_stats_web/views/layout_view.ex
defmodule CodeStatsWeb.LayoutView do
  use CodeStatsWeb, :view

  def get_title(conn) do
    site_name = get_conf(:site_name)

    if conn.assigns[:title] do
      "#{conn.assigns[:title]} – #{site_name}"
    else
      site_name
    end
  end
end

lib/code_stats_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Code::Stats is a free stats tracking service for programmers">
    <meta name="author" content="Mikko Ahlroth">

    <title><%= get_title(@conn) %></title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/frontend/css/frontend.css") %>">

    <link rel="apple-touch-icon" sizes="57x57" href="/frontend/assets/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/frontend/assets/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/frontend/assets/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/frontend/assets/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/frontend/assets/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/frontend/assets/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/frontend/assets/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/frontend/assets/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/frontend/assets/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/frontend/assets/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/frontend/assets/manifest.json">
    <link rel="mask-icon" href="/frontend/assets/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/frontend/assets/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= if is_authed?(@conn) do %>
      <%= tag(:meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", get_current_user(@conn).username)) %>
    <% end %>
  </head>

  <body>
    <header id="nav-stripe" class="stripe">
      <a id="header-logo" class="logo" href="<%= page_path(@conn, :index) %>">
        <img
         src="<%= static_path(@conn, "/frontend/assets/images/Logo.svg") %>"
         alt="<%= get_conf(:site_name) %> logo"
         title="<%= get_conf(:site_name) %>"
        />
      </a>

      <nav id="header-nav" role="navigation">
        <%= if is_authed?(@conn) do %>
          <a href="<%= profile_path(@conn, :my_profile) %>">Profile</a>
          <a href="<%= preferences_path(@conn, :edit) %>">Preferences</a>
          <a href="<%= machine_path(@conn, :list) %>">Machines</a>
          <a href="<%= auth_path(@conn, :logout) %>">Log out</a>
        <% else %>
          <a href="<%= auth_path(@conn, :render_login) %>">Log in</a>
          <a href="<%= auth_path(@conn, :render_signup) %>">Sign up</a>
        <% end %>
      </nav>
    </header>

    <%= if get_flash(@conn, :info) do %>
      <div class="stripe flash-stripe" role="alert">
        <%= get_flash(@conn, :info) %>
      </div>
    <% end %>
    <%= if get_flash(@conn, :success) do %>
      <div class="stripe flash-stripe flash-success" role="alert">
        <%= get_flash(@conn, :success) %>
      </div>
    <% end %>
    <%= if get_flash(@conn, :error) do %>
      <div class="stripe flash-stripe flash-error" role="alert">
        <%= get_flash(@conn, :error) %>
      </div>
    <% end %>

    <%= if false and get_conf(:beta_mode) do %>
      <section class="stripe flash-stripe" role="alert">
        <strong>⚠️ Note!</strong>
        This instance is in beta mode. You can register as normal and use this instance for testing
        purposes, such as for developing a new editor plugin. The database may be reset at any time.
      </section>
    <% end %>

    <main>
      <%= render @view_module, @view_template, assigns %>
    </main>

    <footer id="footer-stripe" class="stripe stripe-accent">
      <section>
        <h6 class="no-margin">Rendered in <%= CodeStatsWeb.RequestTimePlug.calculate_time(@conn) %>.</h6>
        <a href="<%= page_path(@conn, :changes)%>"><%= unquote(Mix.Project.config[:version]) %></a>
        <a href="<%= page_path(@conn, :api_docs) %>">API docs</a>
        <a href="<%= page_path(@conn, :terms) %>">Legal</a>
        <a href="<%= page_path(@conn, :plugins) %>">Plugins</a>
      </section>

      <%= if not Enum.empty?(get_conf(:social_links)) do %>
        <section>
          <h6 class="no-margin">Contact us!</h6>
          <%= for {name, url} <- get_conf(:social_links) do %>
            <a href="<%= url %>"><%= name %></a>
          <% end %>
        </section>
      <% end %>

      <section>
        <p>
          Made with
          <a href="http://elixir-lang.org/">Elixir</a>,
          <a href="http://www.phoenixframework.org/">Phoenix</a>, and
          <a href="https://redom.js.org/">RE:DOM</a>.
        </p>
        <small>
          <%= get_conf(:site_name) %> development sponsored by <a href="https://www.vincit.fi/en/">Vincit Oy</a>, the passionate software company.
        </small>
      </section>
    </footer>

    <script type="text/javascript" src="<%= static_path(@conn, "/frontend/js/frontend.js") %>"></script>
    <%= raw get_conf(:analytics_code) %>
  </body>
</html>

lib/code_stats_web/templates/layout/battle.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Code::Stats is a free stats tracking service for programmers">
    <meta name="author" content="Mikko Ahlroth">

    <title><%= get_conf(:site_name) %> Battle Mode</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/battle/css/battle.css") %>">

    <link rel="apple-touch-icon" sizes="57x57" href="/frontend/assets/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/frontend/assets/apple-touch-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/frontend/assets/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/frontend/assets/apple-touch-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/frontend/assets/apple-touch-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/frontend/assets/apple-touch-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/frontend/assets/apple-touch-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/frontend/assets/apple-touch-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/frontend/assets/apple-touch-icon-180x180.png">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-32x32.png" sizes="32x32">
    <link rel="icon" type="image/png" href="/frontend/assets/android-chrome-192x192.png" sizes="192x192">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-96x96.png" sizes="96x96">
    <link rel="icon" type="image/png" href="/frontend/assets/favicon-16x16.png" sizes="16x16">
    <link rel="manifest" href="/frontend/assets/manifest.json">
    <link rel="mask-icon" href="/frontend/assets/safari-pinned-tab.svg" color="#5bbad5">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/frontend/assets/mstile-144x144.png">
    <meta name="theme-color" content="#ffffff">

    <%= if is_authed?(@conn) do %>
      <%= tag(:meta, name: "channel_token", content: Phoenix.Token.sign(@conn, "user", get_current_user(@conn).username)) %>
    <% end %>
  </head>

  <body>
    <%= render @view_module, @view_template, assigns %>

    <script type="text/javascript" src="<%= static_path(@conn, "/battle/js/battle.js") %>"></script>
    <%= raw get_conf(:analytics_code) %>
  </body>
</html>

lib/code_stats_web/templates/layout/email.text.eex
<%= get_conf(:site_name) %>
===========

<%= render @view_module, @view_template, assigns %>

-----------
This email was sent from <%= get_conf(:site_name) %> <<%= get_conf(:absolute_url) <> page_path(CodeStats.Endpoint, :index) %>>. If you do not wish to receive more emails, you can remove your email address in the preferences page of your account.

Please note that you cannot reply to this email.